# Generated by Django 5.2.7 on 2025-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
